# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: overlay.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'overlay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\roverlay.proto\"(\n\x07Request\x12\x0f\n\x07payload\x18\x01 \x01(\t\x12\x0c\n\x04hops\x18\x02 \x03(\t\"(\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0c\n\x04hops\x18\x02 \x03(\t\"\x10\n\x0eMetricsRequest\"\xb8\x01\n\x0fMetricsResponse\x12\x12\n\nprocess_id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x0c\n\x04team\x18\x03 \x01(\t\x12\x17\n\x0f\x61\x63tive_requests\x18\x04 \x01(\x05\x12\x14\n\x0cmax_capacity\x18\x05 \x01(\x05\x12\x12\n\nis_healthy\x18\x06 \x01(\x08\x12\x12\n\nqueue_size\x18\x07 \x01(\x05\x12\x1e\n\x16\x61vg_processing_time_ms\x18\x08 \x01(\x02\x32\x62\n\x0bOverlayNode\x12 \n\x07\x46orward\x12\x08.Request\x1a\t.Response\"\x00\x12\x31\n\nGetMetrics\x12\x0f.MetricsRequest\x1a\x10.MetricsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'overlay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=17
  _globals['_REQUEST']._serialized_end=57
  _globals['_RESPONSE']._serialized_start=59
  _globals['_RESPONSE']._serialized_end=99
  _globals['_METRICSREQUEST']._serialized_start=101
  _globals['_METRICSREQUEST']._serialized_end=117
  _globals['_METRICSRESPONSE']._serialized_start=120
  _globals['_METRICSRESPONSE']._serialized_end=304
  _globals['_OVERLAYNODE']._serialized_start=306
  _globals['_OVERLAYNODE']._serialized_end=404
# @@protoc_insertion_point(module_scope)
