# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: overlay.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'overlay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\roverlay.proto\x12\x07overlay\"(\n\x07Request\x12\x0f\n\x07payload\x18\x01 \x01(\t\x12\x0c\n\x04hops\x18\x02 \x03(\t\"(\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0c\n\x04hops\x18\x02 \x03(\t2=\n\x0bOverlayNode\x12.\n\x07\x46orward\x12\x10.overlay.Request\x1a\x11.overlay.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'overlay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=26
  _globals['_REQUEST']._serialized_end=66
  _globals['_RESPONSE']._serialized_start=68
  _globals['_RESPONSE']._serialized_end=108
  _globals['_OVERLAYNODE']._serialized_start=110
  _globals['_OVERLAYNODE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
